### ISSUE TITLE
Housekeeping reports show 0 after upgrade - timing issue

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#168] opened 2018-10-21 14:27 UTC
We upgraded to 2.14.7 and the Hubble stats for today (the logs from yesterday) show 0 results for three reports: Git Traffic, Git Requests, and API Requests. All of the other charts seem to be OK. We are using the latest master branch release of Hubble.

The issue is that the logs were cleared out for the upgrade and we do not yet have the rotated logs that Hubble would be using. Once the new GHE release has run for longer than 24 hours then we will have rotated logs to review.

So this is just a timing issue. Hubble ran soon after the upgrade and GHE had not yet had a chance to run long enough to rotate logs that Hubble uses for certain reports.

**Comment by pluehne** [comment] 2018-10-24 23:05
Hi, @toddocon! Thanks for reporting this issue.

I’ll try to replicate this on a 2.14 instance. In the meantime, it would help if you could execute the following scripts directly on your appliance: [`api-requests.sh`](https://github.com/Autodesk/hubble/blob/master/updater/scripts/api-requests.sh), [`git-download.sh`](https://github.com/Autodesk/hubble/blob/master/updater/scripts/git-download.sh), and [`git-requests.sh`](https://github.com/Autodesk/hubble/blob/master/updater/scripts/git-requests.sh). I’d like to see whether you get some specific error messages that would help us debug this issue.

**Comment by pluehne** [comment] 2018-10-26 00:09
@toddocon: Oh, I had just read the notification e-mail from GitHub on your new issue, but I didn’t notice that you updated the text in the meantime.

Thank you for explaining that this was only due to the fact that your fresh appliance didn’t have any logs available. This make sense and should indeed explain the issue :slightly_smiling_face:.

I was just trying to reproduce the missing values, but everything worked smoothly on my end, so I ended up wondering what could be wrong on your end. I agree, timing seems to be the likely cause.

Unfortunately, I don’t see anything we could do to prevent the 1-day data loss after upgrades. Even copying over old logs to newer appliances isn’t really safe, because the log format frequently changes from one version to another, and our checks test against the currently installed version of GitHub Enterprise and not the one the log files were created on necessarily. Do you have other suggestions on how we could support GitHub Enterprise upgrades more seamlessly?

Just to make sure that there isn’t another GitHub-Enterprise-2.14-related issue lingering around, could you confirm that you now obtain sensible data after the logs were rotated?

**Comment by pluehne** [comment] 2018-11-23 17:45
@toddocon: I’m closing this now. If you’re still encountering issues specific to GitHub Enterprise 2.14, feel free to open this issue again :slightly_smiling_face:.

**Closed by pluehne** 2018-11-23 17:45 UTC
Labels: bug
